import { Template } from 'e2b'

export const template = Template()
  .fromImage('ubuntu:22.04')
  .setUser('root')
  .setWorkdir('/')
  .setEnvs({
    'DEBIAN_FRONTEND': 'noninteractive',
  })
  .runCmd('apt-get update && apt-get install -y curl wget unzip jq git ca-certificates gnupg && rm -rf /var/lib/apt/lists/*')
  .runCmd('curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && apt-get install -y nodejs && rm -rf /var/lib/apt/lists/*')
  .runCmd('npm install -g @anthropic-ai/claude-code')
  .runCmd('npx playwright install-deps chromium || true')
  .runCmd('mkdir -p /workspace/agent-runtime')
  .copy('package*.json', '/workspace/agent-runtime/')
  .copy('tsconfig.json', '/workspace/agent-runtime/')
  .setWorkdir('/workspace/agent-runtime')
  .runCmd('npm install')
  .copy('src', '/workspace/agent-runtime/src')
  .copy('.claude', '/workspace/agent-runtime/.claude')
  .copy('server.js', '/workspace/server.js')
  .runCmd('node --version && npm --version && claude --version')
  .setWorkdir('/workspace')
  .setUser('user')
  .setStartCmd('sudo node /workspace/server.js', 'sleep 20')